kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: rhsso73-oraclejdbc-build
  labels:
    name: rhsso73-oraclejdbc-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'redhat-sso73-openshift-oracle:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'redhat-sso73-openshift:latest'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM openshift/redhat-sso73-openshift:latest
      USER root
      COPY ./actions.cli ./postconfigure.sh /opt/eap/extensions/
      RUN chown jboss:jboss /opt/eap/extensions/* && chmod 555 /opt/eap/extensions/*.* && chmod 777 /opt/eap/extensions/*.sh
      USER jboss
      CMD ["/opt/eap/bin/openshift-launch.sh"]
    secrets:
      - secret:
          name: rhsso73-oraclejdbc-build-files
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
